---
# .mega-linter.yml
# Optimized for PowerShell, Shell, Documentation, and Security.

# --- Core Settings ---
VALIDATE_ALL_CODEBASE: true
APPLY_FIXES: none

# --- Enable/Disable Strategy ---
# We use ENABLE_LINTERS for max speed and security.
# Remove the large 'DISABLE' block as it is now redundant.

# --- Linter Selection ---
ENABLE_LINTERS:
  # 1. Languages
  - BASH_EXEC # Basic shell script syntax check
  - BASH_SHELLCHECK # Advanced Shell script linter (your core need)
  - POWERSHELL_POWERSHELL # PowerShell linter (PSScriptAnalyzer)
  - JAVASCRIPT_ES # JavaScript linter (ESLint)

  # 2. Formats
  - YAML_YAMLLINT # General YAML config files (CI, mkdocs, etc.)
  - YAML_V8R # YAML schema validation
  - JSON_JSONLINT # General JSON files
  - JSON_V8R # JSON schema validation
  - JSON_NPM_PACKAGE_JSON_LINT # Specific checks for package.json integrity (Keep this since you use pnpm)
  - MARKDOWN_MARKDOWNLINT # Markdown file structure and style
  - MARKDOWN_MARKDOWN_LINK_CHECK # Checks for broken links in documentation

  # 3. Tooling formats
  - ACTION_ACTIONLINT # GitHub Actions workflow files (.github/workflows/*.yml)
  - DOCKERFILE_HADOLINT # Dockerfile linter (hadolint)

  # 4. Other
  - REPOSITORY_GIT_DIFF # Checks for changes in the repository
  - REPOSITORY_GITLEAKS # Secrets scanning in Git history
  - REPOSITORY_GRYPE # Scans dependencies and configurations for known vulnerabilities
  - REPOSITORY_LS_LINT # fast file and directory name linter that helps maintain consistent naming conventions across your project.
  - REPOSITORY_SECRETLINT # General secrets pattern detection
  - REPOSITORY_SEMGREP # Static code analysis for security vulnerabilities and coding standards
  - REPOSITORY_SYFT # Scans dependencies and configurations for known vulnerabilities
  - REPOSITORY_TRIVY # Scans dependencies and configurations for known vulnerabilities
  - REPOSITORY_TRUFFLEHOG # Advanced secrets scanning

  # 4.1 Spell
  # - SPELL_CSPELL # Spelling check (Crucial)
  # - SPELL_VALE # Documentation style and grammar check

# --- Configuration Arguments ---
# Arguments for linters that need specific settings
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
PYTHON_PYRIGHT_CONFIG_FILE: pyproject.toml

# Excludes
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (\.vscode/)
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: (docs/|\.github/) # Optional: Exclude docs/ or .github/ from general YAML linting if they use specific standards
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: (mkdocs.yml)
YAML_V8R_FILTER_REGEX_EXCLUDE: (\.github/config|mkdocs.yml)
MARKDOWN_FILTER_REGEX_EXCLUDE: (license\.md|docs/licenses|LICENSE|LICENSES)
SPELL_VALE_FILE_EXTENSIONS:
  - .md
SPELL_FILTER_REGEX_EXCLUDE: (\.github|docs/licenses|LICENSE|LICENSES)
DOCKERFILE_HADOLINT_ARGUMENTS:
  - --ignore DL3003
  - --ignore DL3007
  - --ignore DL3013
  - --ignore DL3016
  - --ignore DL3018
  - --ignore DL3028
  - --ignore DL3059
  - --ignore DL4001
  - --ignore DL4006
  - --ignore SC2015
  - --ignore SC2016
  - --ignore SC2039
  - --ignore SC2086
  - --ignore SC1091
  - --ignore SC3046
REPOSITORY_TRIVY_ARGUMENTS:
  - --skip-dirs
  - .automation/test
  - --skip-dirs
  - .venv

# --- Exclusion List (To avoid running on third-party folders) ---
EXCLUDED_DIRECTORIES:
  - node_modules
  - .venv
  - dist
  - .git
# Reporting
REPORTERS_MARKDOWN_SUMMARY_TYPE: sections
SHOW_ELAPSED_TIME: true

# PRE_COMMANDS:
SPELL_CSPELL_PRE_COMMANDS:
  - command: echo "Preparing cspell..."
  - command: npm install
  - command: echo "Pre-command completed."
